Add missing kTargetHostSuffix and kTargetPathSuffix constants
Fixes compilation errors:
- error: use of undeclared identifier 'kTargetHostSuffix'
- error: use of undeclared identifier 'kTargetPathSuffix'

These constants are now defined as static strings that will be used
to match manifest API requests from limbus-company.com.